### PR TITLE
Convert invalid chars to ! for backup files

### PR DESCRIPTION
**Pull request by rasa**
Tested and working locally.

### CODE REVIEW

**Comment by rasa** [comment]
Here's the resultant diff:
```diff
--- ./src/files.c.bak	2023-01-30 19:18:22.082545600 -0800
+++ ./src/files.c	2023-01-30 19:18:22.798748400 -0800
@@ -1612,7 +1612,7 @@
 		 * just use the file-name portion of the given path. */
 		if (thename) {
 			for (int i = 0; thename[i] != '\0'; i++)
-				if (thename[i] == '/')
+				if (strchr("<>:\"/\\|?*", thename[i]))
 					thename[i] = '!';
 		} else
 			thename = copy_of(tail(realname));

```

**Comment by okibcn** [comment]
I really would remove the lines [1613-1617] as it really doesn't add too much. It is ok only when editing the same name in different folders, but this is the original code, so we have to keep it as close as possible.

Thanks

**Comment by rasa** [comment]
> I really would remove the lines [1613-1617] as it really doesn't add too much. It is ok only when editing the same name in different folders, but this is the original code, so we have to keep it as close as possible.

@okibcn I'm not sure I follow. The code allows a file edited in any directory to have a backup file stored in `.nanorc`'s `backupdir`. An example is:
`C!!github!rasa!nano-for-windows!.github!workflows!Xbuild4Windows.yml`
If you remove lines 1613-1617, the backup function would then fail, right?

**Comment by okibcn** [comment]
No, it wont. Instead the whole path, it will use the filename adding `~` and a sequential number in case of editing the same filename in different folders. In your example, it would be `Xbuild4Windows.yml~1`

**Comment by rasa** [comment]
> No, it won't. Instead of taking the whole path, it will use the filename adding `~` and a sequential number in case of editing the same filename in different folders. In your example, it would be `Xbuild4Windows.yml~1`. If you edit another file with the same name in another folder, it would be `Xbuild4Windows.yml~2`, etc...

@okibcn That wasn't my experience. nano was annoying displaying popup messages whenever I saved a file without this fix:

https://user-images.githubusercontent.com/220772/215816931-2c6427e3-c073-4d13-ab60-c30c9e12e839.mp4

**Comment by okibcn** [comment]
Yes, backups had that problem. But I was considering deleting those lines as a quick solution. Reviewing The backup functions is something I haven't gotten into. Thanks for taking care of this one. There are some other lines that will probably need a fix.

**Pull request merged**
